// @vitest-environment node
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { generateCaseStudyDisplayImages } from './generate-case-study-display-images.js';

const fixtureRoots = [];
const sourcePath = '/assets/case-studies/fixture-source.webp';
const sourceBytes = Buffer.from('UklGRiYAAABXRUJQVlA4IBoAAAAwAQCdASoBAAEAAQAaJaQAA3AA/v5HgAAAAA==', 'base64');
const publication = [{ image: { src: sourcePath }, gallery: [], sections: [] }];

afterEach(() => fixtureRoots.splice(0).forEach((root) => rmSync(root, { recursive: true, force: true })));

const createFixture = () => {
  const root = mkdtempSync(path.join(tmpdir(), 'case-study-display-generator-'));
  fixtureRoots.push(root);
  const assetDirectory = path.join(root, 'public/assets/case-studies');
  mkdirSync(assetDirectory, { recursive: true });
  writeFileSync(path.join(assetDirectory, 'fixture-source.webp'), sourceBytes);
  return root;
};

const registryFor = (binding) => ({
  [sourcePath]: {
    sourceSha256: binding.sourceSha256,
    display: {
      src: binding.displayPath,
      sha256: binding.displaySha256,
      width: binding.displayWidth,
      height: binding.displayHeight,
    },
  },
});

const generateFixture = async (root) => {
  const result = await generateCaseStudyDisplayImages({ root, publication, registry: {}, mode: 'write' });
  return { binding: result.bindings[0], registry: registryFor(result.bindings[0]) };
};

describe('case-study display generator', () => {
  it('regenerates and verifies the exact committed derivative bytes', async () => {
    const root = createFixture();
    const { binding, registry } = await generateFixture(root);
    const derivativeFile = path.join(root, 'public', binding.displayPath.slice(1));
    const committedBytes = readFileSync(derivativeFile);

    await expect(generateCaseStudyDisplayImages({ root, publication, registry, mode: 'check' }))
      .resolves.toMatchObject({ uniqueAssets: 1 });

    const tamperedBytes = Buffer.concat([committedBytes, Buffer.from([0])]);
    writeFileSync(derivativeFile, tamperedBytes);
    await expect(generateCaseStudyDisplayImages({ root, publication, registry, mode: 'check' }))
      .rejects.toThrow(/does not match regenerated bytes/i);
    expect(readFileSync(derivativeFile)).toEqual(tamperedBytes);
  });

  it('rejects stale source and content-addressed filename bindings', async () => {
    const root = createFixture();
    const { binding, registry } = await generateFixture(root);
    const sourceFile = path.join(root, 'public', sourcePath.slice(1));

    writeFileSync(sourceFile, Buffer.concat([sourceBytes, Buffer.from([0])]));
    await expect(generateCaseStudyDisplayImages({ root, publication, registry, mode: 'check' }))
      .rejects.toThrow(/source changed without regenerating/i);
    writeFileSync(sourceFile, sourceBytes);

    const staleRegistry = structuredClone(registry);
    staleRegistry[sourcePath].display.src = binding.displayPath.replace(binding.displaySha256.slice(0, 12), 'deadbeefdead');
    await expect(generateCaseStudyDisplayImages({ root, publication, registry: staleRegistry, mode: 'check' }))
      .rejects.toThrow(/filename is stale/i);
  });
});
